name: Android avd

on:
  # push:
  #   branches:
  #   - master
  #   paths:
  #   - 'packages/**'
  #   - 'root-packages/**'
  #   - 'x11-packages/**'
  # pull_request:
  #   paths:
  #   - 'packages/**'
  #   - 'root-packages/**'
  #   - 'x11-packages/**'
  workflow_dispatch:
    # inputs:
    #   packages:
    #     description: "A space-separated names of packages selected for rebuilding"
    #     required: true

jobs:
  test_android:
    name: Test Android builds
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [30]
        arch: [armeabi-v7a, arm64-v8a] #x86_64, x86]
    env:
      TERMUX: v0.118.0
    steps:
      - uses: actions/checkout@v3

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/avd/*/snapshots/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.arch }}+termux-${{ env.TERMUX }}

      - name: Create and cache emulator image
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          ram-size: 2048M
          disk-size: 5120M
          target: google_apis
          force-avd-creation: true
          emulator-options: -no-snapshot-load -noaudio -no-boot-anim -camera-back none
          script: |
            wget https://github.com/termux/termux-app/releases/download/${{ env.TERMUX }}/termux-app_${{ env.TERMUX }}+github-debug_${{ matrix.arch }}.apk
            ./android-commands.sh snapshot termux-app_${{ env.TERMUX }}+github-debug_${{ matrix.arch }}.apk
            adb -s emulator-5556 emu avd snapshot save ${{ matrix.api-level }}-${{ matrix.arch }}+termux-${{ env.TERMUX }}
            echo "Emulator image created."
            pkill -9 qemu-system-x86_64

      - name: Build and Test on Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          ram-size: 2048M
          disk-size: 5120M
          force-avd-creation: false
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -snapshot ${{ matrix.api-level }}-${{ matrix.arch }}+termux-${{ env.TERMUX }}
          script: |
            ./android-commands.sh test
